// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v0.1/claude/repositories/clone": {
            "post": {
                "description": "GitHub 사용자/조직의 모든 저장소를 로컬 디렉토리에 복제합니다.\n\n**기능:**\n- GitHub API를 통해 지정된 사용자/조직의 모든 저장소 목록을 가져옵니다\n- 각 저장소를 지정된 로컬 디렉토리에 Git clone으로 복제합니다\n- 이미 존재하는 저장소는 건너뛰어 중복 다운로드를 방지합니다\n- 기본 사용자: JokerTrickster, 기본 경로: ~/project/git-repository/JokerTrickster\n\n**요청 예시:**\n` + "`" + `` + "`" + `` + "`" + `json\n{\n\"github_username\": \"JokerTrickster\",\n\"github_token\": \"ghp_xxxxxxxxxxxx\"\n}\n` + "`" + `` + "`" + `` + "`" + `\n\n**응답 예시:**\n` + "`" + `` + "`" + `` + "`" + `json\n{\n\"status\": \"success\",\n\"total_repositories\": 15,\n\"cloned_count\": 12,\n\"skipped_count\": 3,\n\"failed_count\": 0,\n\"details\": [\n{\n\"name\": \"workflow\",\n\"clone_url\": \"https://github.com/JokerTrickster/workflow.git\",\n\"status\": \"cloned\",\n\"local_path\": \"~/project/git-repository/JokerTrickster/workflow\"\n}\n]\n}\n` + "`" + `` + "`" + `` + "`" + `\n\n■ **에러 코드 (HTTP 400)**\n- PARAM_BAD : 파라미터 오류 또는 유효성 검증 실패\n- GITHUB_USER_NOT_FOUND : GitHub 사용자/조직이 존재하지 않음\n- GITHUB_USERNAME_INVALID : GitHub 사용자명 형식이 올바르지 않음\n- GITHUB_API_RATE_LIMIT : GitHub API 호출 한도 초과\n- GITHUB_API_AUTH_FAILED : GitHub API 인증 실패\n\n■ **에러 코드 (HTTP 500)**\n- INTERNAL_SERVER : 내부 로직 처리 실패\n- DIRECTORY_CREATE_FAILED : 대상 디렉토리 생성 실패\n- GIT_CLONE_FAILED : Git 복제 작업 실패\n- GITHUB_API_ERROR : GitHub API 서버 오류",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "claude"
                ],
                "summary": "GitHub 저장소 일괄 복제",
                "parameters": [
                    {
                        "description": "저장소 복제 요청",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ReqCloneRepositories"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "복제 작업 완료",
                        "schema": {
                            "$ref": "#/definitions/request.ResCloneRepositories"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {}
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {}
                    }
                }
            }
        },
        "/v0.1/claude/tasks/run": {
            "post": {
                "description": "지정된 저장소에서 Claude CLI 명령어를 실행합니다\n\n**기능:**\n- repository_name으로 지정된 저장소(~/project/git-repository/JokerTrickster/{repository_name})에서 작업 실행\n- interactive 모드: 여러 작업을 순차적으로 실행 (줄바꿈 또는 세미콜론으로 구분)\n- 일반 모드: 단일 작업을 한 번에 실행\n- --dangerously-skip-permissions 플래그로 승인 요청 없이 자동 실행\n\n**필수 파라미터:**\n- tasks: 실행할 작업 내용\n- repository_name: 작업할 저장소 이름 (필수)\n\n**Interactive 모드 예시:**\n` + "`" + `` + "`" + `` + "`" + `json\n{\n\"tasks\": \"echo 첫번째 작업\\necho 두번째 작업\\necho 세번째 작업\",\n\"repository_name\": \"JokerTrickster\",\n\"interactive\": true\n}\n` + "`" + `` + "`" + `` + "`" + `\n\n■ **에러 코드 (HTTP 400)**\n- PARAM_BAD : 파라미터 오류 또는 유효성 검증 실패\n- REPOSITORY_NAME_REQUIRED : repository_name 필수 파라미터 누락\n\n■ **에러 코드 (HTTP 500)**\n- INTERNAL_SERVER : 내부 로직 처리 실패\n- REPOSITORY_NOT_FOUND : 저장소 디렉토리를 찾을 수 없음\n- CLAUDE_CLI_EXECUTION_FAILED : Claude CLI 실행 실패",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "claude"
                ],
                "summary": "태스크 실행 (Claude CLI)",
                "parameters": [
                    {
                        "description": "작업 실행 요청",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ReqRunTasksClaude"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "작업 실행 완료",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {}
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "request.RepositoryResult": {
            "type": "object",
            "properties": {
                "clone_url": {
                    "description": "복제 URL",
                    "type": "string"
                },
                "error_message": {
                    "description": "에러 메시지 (실패시)",
                    "type": "string"
                },
                "local_path": {
                    "description": "로컬 경로 (성공시)",
                    "type": "string"
                },
                "name": {
                    "description": "저장소 이름",
                    "type": "string"
                },
                "status": {
                    "description": "상태 (cloned/skipped/failed)",
                    "type": "string"
                }
            }
        },
        "request.ReqCloneRepositories": {
            "type": "object",
            "properties": {
                "github_token": {
                    "description": "GitHub 토큰 (옵션)",
                    "type": "string"
                },
                "github_username": {
                    "description": "GitHub 사용자명/조직명 (기본값: JokerTrickster)",
                    "type": "string"
                },
                "target_directory": {
                    "description": "대상 디렉토리 (옵션)",
                    "type": "string"
                }
            }
        },
        "request.ReqRunTasksClaude": {
            "type": "object",
            "required": [
                "provider",
                "repository_name",
                "tasks"
            ],
            "properties": {
                "cmd": {
                    "description": "Claude CLI 명령어 경로 (옵션)",
                    "type": "string"
                },
                "continue_task": {
                    "description": "기존 작업 이어서 하기 (옵션)",
                    "type": "boolean"
                },
                "interactive": {
                    "description": "대화형 모드: 여러 작업을 순차 실행",
                    "type": "boolean"
                },
                "provider": {
                    "description": "AI 모델 제공자 (예: \"claude\") (필수)",
                    "type": "string"
                },
                "repository_name": {
                    "description": "레포지토리 이름 (필수)",
                    "type": "string"
                },
                "tasks": {
                    "description": "실행할 작업 내용",
                    "type": "string"
                },
                "working_dir": {
                    "description": "작업 디렉토리 (옵션)",
                    "type": "string"
                }
            }
        },
        "request.ResCloneRepositories": {
            "type": "object",
            "properties": {
                "cloned_count": {
                    "description": "복제된 저장소 수",
                    "type": "integer"
                },
                "details": {
                    "description": "개별 저장소 결과 상세",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.RepositoryResult"
                    }
                },
                "failed_count": {
                    "description": "실패한 저장소 수",
                    "type": "integer"
                },
                "skipped_count": {
                    "description": "건너뛴 저장소 수",
                    "type": "integer"
                },
                "status": {
                    "description": "전체 작업 상태 (success/failed/partial)",
                    "type": "string"
                },
                "total_repositories": {
                    "description": "전체 저장소 수",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7001",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Local Backend API",
	Description:      "This is a local backend server API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
